### ISSUE TITLE
Missing env vars into the descriptor

### ISSUE THREAD

**Issue by nirekin** [lagoon-platform/model#7]
We must allow the end user to specify `environment variables` in all the model object which are currently supporting `params:`

The implementation of `environment variables` should offer :
* A way to overwrite  `environment variables` as it is currently possible with `params:`
* A way to define an environment variable key into the descriptor and to read, at runtime, its value from outside of the descriptor. 
For example using something like 
```yaml
providers:
  aws:
    repository: lagoon_repository/aws-provider
  env:
    key1:value1
    key2:${client_key1}
```

as the end user has the opportunity through the *CLI* to pass its own environment variables files the main idea behind this is  to pick, at runtime, a value into this file to substitute the one into the descriptor.
